dependencias adicionadas

diff --git a/.github/workflows/workflow-test-front.yml b/.github/workflows/workflow-test-front.yml
--- a/.github/workflows/workflow-test-front.yml
+++ b/.github/workflows/workflow-test-front.yml
@@ -1,4 +1,4 @@
-name: Continuos Integration-FE
+name: Continuous Integration-FE
 on:
   pull_request:
     branches:
@@ -16,6 +16,16 @@ jobs:
         uses: actions/setup-node@v2
         with:
           node-version: 16.x
+
+      - name: List directory contents
+        run: ls -la
+
+      - name: Verify package.json existence
+        run: |
+          if [ ! -f package.json ]; then
+            echo "package.json not found!"
+            exit 1
+          fi
 
       - name: Install dependencies, build, and test
         run: |
